version: '3.8'

x-app_environment: &app_environment
  environment:
    # API
    - DEBUG=True
    - API_DOCS_ENABLE=True
    - SECRET_KEY=django-insecure-nrx08t@9@14vb5xic&^bb#&=vt9c3!3r$sw50x8gvrd6g8=*rs
    # DB
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST=db
    - POSTGRES_PORT=5432
    - POSTGRES_NAME=postgres
    - POSTGRES_USER=postgres
    # Telegram
    - TOKEN=7193240248:AAGLX2xQsMFegt4_1n5IwhfnMyvWR5wuZZY
    - API_HOST=api

services:
  db:
    image: postgres:13.3-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    <<: *app_environment
    networks:
      - my_network

  api:
    build:
      context: .
    <<: *app_environment
    container_name: api
    command:  python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./api/:/app/
    restart: unless-stopped
    networks:
      - my_network

  tele_bot:
    build:
      context: .
    <<: *app_environment
    command: python handlers.py
    volumes:
      - ./tele_bot/:/app/
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver : bridge

volumes:
  postgresdata: