# Generated by Django 4.2.6 on 2024-04-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись на прием', 'verbose_name_plural': 'Записи на прием'},
        ),
    ]
