# Generated by Django 4.2.6 on 2024-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_alter_appointment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
